language: scala
dist: xenial
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.2
jdk:
  - oraclejdk8
matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.8
install:
  - sudo apt-get --yes install python-pygments
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
- git diff --exit-code # check scalariform
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.cache/coursier/v1
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
